class Autogenerated {
  String? createdBy;
  int? createdAt;
  String? lastModifiedBy;
  int? lastModifiedAt;
  String? name;
  String? description;
  String? controllerId;
  String? updateStatus;
  int? lastControllerRequestAt;
  String? address;
  PollStatus? pollStatus;
  String? securityToken;
  bool? requestAttributes;
  Links? lLinks;

  Autogenerated(
      {this.createdBy,
      this.createdAt,
      this.lastModifiedBy,
      this.lastModifiedAt,
      this.name,
      this.description,
      this.controllerId,
      this.updateStatus,
      this.lastControllerRequestAt,
      this.address,
      this.pollStatus,
      this.securityToken,
      this.requestAttributes,
      this.lLinks});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    createdBy = json['createdBy'];
    createdAt = json['createdAt'];
    lastModifiedBy = json['lastModifiedBy'];
    lastModifiedAt = json['lastModifiedAt'];
    name = json['name'];
    description = json['description'];
    controllerId = json['controllerId'];
    updateStatus = json['updateStatus'];
    lastControllerRequestAt = json['lastControllerRequestAt'];
    address = json['address'];
    pollStatus = json['pollStatus'] != null
        ? PollStatus.fromJson(json['pollStatus'])
        : null;
    securityToken = json['securityToken'];
    requestAttributes = json['requestAttributes'];
    lLinks = json['_links'] != null ? Links.fromJson(json['_links']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['createdBy'] = createdBy;
    data['createdAt'] = createdAt;
    data['lastModifiedBy'] = lastModifiedBy;
    data['lastModifiedAt'] = lastModifiedAt;
    data['name'] = name;
    data['description'] = description;
    data['controllerId'] = controllerId;
    data['updateStatus'] = updateStatus;
    data['lastControllerRequestAt'] = lastControllerRequestAt;
    data['address'] = address;
    if (pollStatus != null) {
      data['pollStatus'] = pollStatus!.toJson();
    }
    data['securityToken'] = securityToken;
    data['requestAttributes'] = requestAttributes;
    if (lLinks != null) {
      data['_links'] = lLinks!.toJson();
    }
    return data;
  }
}

class PollStatus {
  int? lastRequestAt;
  int? nextExpectedRequestAt;
  bool? overdue;

  PollStatus({this.lastRequestAt, this.nextExpectedRequestAt, this.overdue});

  PollStatus.fromJson(Map<String, dynamic> json) {
    lastRequestAt = json['lastRequestAt'];
    nextExpectedRequestAt = json['nextExpectedRequestAt'];
    overdue = json['overdue'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['lastRequestAt'] = lastRequestAt;
    data['nextExpectedRequestAt'] = nextExpectedRequestAt;
    data['overdue'] = overdue;
    return data;
  }
}

class Links {
  Self? self;
  Self? assignedDS;
  Self? installedDS;
  Self? attributes;
  Self? actions;
  Metadata? metadata;

  Links(
      {this.self,
      this.assignedDS,
      this.installedDS,
      this.attributes,
      this.actions,
      this.metadata});

  Links.fromJson(Map<String, dynamic> json) {
    self = json['self'] != null ? Self.fromJson(json['self']) : null;
    assignedDS =
        json['assignedDS'] != null ? Self.fromJson(json['assignedDS']) : null;
    installedDS =
        json['installedDS'] != null ? Self.fromJson(json['installedDS']) : null;
    attributes =
        json['attributes'] != null ? Self.fromJson(json['attributes']) : null;
    actions = json['actions'] != null ? Self.fromJson(json['actions']) : null;
    metadata =
        json['metadata'] != null ? Metadata.fromJson(json['metadata']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (self != null) {
      data['self'] = self!.toJson();
    }
    if (assignedDS != null) {
      data['assignedDS'] = assignedDS!.toJson();
    }
    if (installedDS != null) {
      data['installedDS'] = installedDS!.toJson();
    }
    if (attributes != null) {
      data['attributes'] = attributes!.toJson();
    }
    if (actions != null) {
      data['actions'] = actions!.toJson();
    }
    if (metadata != null) {
      data['metadata'] = metadata!.toJson();
    }
    return data;
  }
}

class Self {
  String? href;

  Self({this.href});

  Self.fromJson(Map<String, dynamic> json) {
    href = json['href'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['href'] = href;
    return data;
  }
}

class Metadata {
  String? href;
  bool? templated;

  Metadata({this.href, this.templated});

  Metadata.fromJson(Map<String, dynamic> json) {
    href = json['href'];
    templated = json['templated'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['href'] = href;
    data['templated'] = templated;
    return data;
  }
}
